// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package bff

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// CreateDashboardCreateDashboard includes the requested fields of the GraphQL type Dashboard.
type CreateDashboardCreateDashboard struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetId returns CreateDashboardCreateDashboard.Id, and is useful for accessing the field via an interface.
func (v *CreateDashboardCreateDashboard) GetId() string { return v.Id }

// GetName returns CreateDashboardCreateDashboard.Name, and is useful for accessing the field via an interface.
func (v *CreateDashboardCreateDashboard) GetName() string { return v.Name }

// CreateDashboardResponse is returned by CreateDashboard on success.
type CreateDashboardResponse struct {
	// Create a new dashboard
	CreateDashboard CreateDashboardCreateDashboard `json:"createDashboard"`
}

// GetCreateDashboard returns CreateDashboardResponse.CreateDashboard, and is useful for accessing the field via an interface.
func (v *CreateDashboardResponse) GetCreateDashboard() CreateDashboardCreateDashboard {
	return v.CreateDashboard
}

// CreateDebugDashboardCreateDebugDashboard includes the requested fields of the GraphQL type Dashboard.
type CreateDebugDashboardCreateDebugDashboard struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetId returns CreateDebugDashboardCreateDebugDashboard.Id, and is useful for accessing the field via an interface.
func (v *CreateDebugDashboardCreateDebugDashboard) GetId() string { return v.Id }

// GetName returns CreateDebugDashboardCreateDebugDashboard.Name, and is useful for accessing the field via an interface.
func (v *CreateDebugDashboardCreateDebugDashboard) GetName() string { return v.Name }

// CreateDebugDashboardResponse is returned by CreateDebugDashboard on success.
type CreateDebugDashboardResponse struct {
	// Create a debug dashboard from uploaded emissions and config
	CreateDebugDashboard CreateDebugDashboardCreateDebugDashboard `json:"createDebugDashboard"`
}

// GetCreateDebugDashboard returns CreateDebugDashboardResponse.CreateDebugDashboard, and is useful for accessing the field via an interface.
func (v *CreateDebugDashboardResponse) GetCreateDebugDashboard() CreateDebugDashboardCreateDebugDashboard {
	return v.CreateDebugDashboard
}

// GetBranchMetricsSetsBranchConfigVersion includes the requested fields of the GraphQL type BranchConfigVersion.
type GetBranchMetricsSetsBranchConfigVersion struct {
	// List all metrics sets defined in this config version
	MetricsSets []GetBranchMetricsSetsBranchConfigVersionMetricsSetsBranchMetricsSet `json:"metricsSets"`
}

// GetMetricsSets returns GetBranchMetricsSetsBranchConfigVersion.MetricsSets, and is useful for accessing the field via an interface.
func (v *GetBranchMetricsSetsBranchConfigVersion) GetMetricsSets() []GetBranchMetricsSetsBranchConfigVersionMetricsSetsBranchMetricsSet {
	return v.MetricsSets
}

// GetBranchMetricsSetsBranchConfigVersionMetricsSetsBranchMetricsSet includes the requested fields of the GraphQL type BranchMetricsSet.
// The GraphQL type's documentation follows.
//
// A metrics set definition from a branch config
type GetBranchMetricsSetsBranchConfigVersionMetricsSetsBranchMetricsSet struct {
	Name string `json:"name"`
}

// GetName returns GetBranchMetricsSetsBranchConfigVersionMetricsSetsBranchMetricsSet.Name, and is useful for accessing the field via an interface.
func (v *GetBranchMetricsSetsBranchConfigVersionMetricsSetsBranchMetricsSet) GetName() string {
	return v.Name
}

// GetBranchMetricsSetsResponse is returned by GetBranchMetricsSets on success.
type GetBranchMetricsSetsResponse struct {
	// Returns a specific config version, or the latest if version_id is not provided.
	BranchConfigVersion GetBranchMetricsSetsBranchConfigVersion `json:"branchConfigVersion"`
}

// GetBranchConfigVersion returns GetBranchMetricsSetsResponse.BranchConfigVersion, and is useful for accessing the field via an interface.
func (v *GetBranchMetricsSetsResponse) GetBranchConfigVersion() GetBranchMetricsSetsBranchConfigVersion {
	return v.BranchConfigVersion
}

// GetDashboardDashboard includes the requested fields of the GraphQL type Dashboard.
type GetDashboardDashboard struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	IsStale   bool   `json:"isStale"`
	LastRanAt string `json:"lastRanAt"`
}

// GetId returns GetDashboardDashboard.Id, and is useful for accessing the field via an interface.
func (v *GetDashboardDashboard) GetId() string { return v.Id }

// GetName returns GetDashboardDashboard.Name, and is useful for accessing the field via an interface.
func (v *GetDashboardDashboard) GetName() string { return v.Name }

// GetIsStale returns GetDashboardDashboard.IsStale, and is useful for accessing the field via an interface.
func (v *GetDashboardDashboard) GetIsStale() bool { return v.IsStale }

// GetLastRanAt returns GetDashboardDashboard.LastRanAt, and is useful for accessing the field via an interface.
func (v *GetDashboardDashboard) GetLastRanAt() string { return v.LastRanAt }

// GetDashboardResponse is returned by GetDashboard on success.
type GetDashboardResponse struct {
	// Get a single dashboard by ID
	Dashboard GetDashboardDashboard `json:"dashboard"`
}

// GetDashboard returns GetDashboardResponse.Dashboard, and is useful for accessing the field via an interface.
func (v *GetDashboardResponse) GetDashboard() GetDashboardDashboard { return v.Dashboard }

type MetricsTemplate struct {
	Contents string `json:"contents"`
	Name     string `json:"name"`
}

// GetContents returns MetricsTemplate.Contents, and is useful for accessing the field via an interface.
func (v *MetricsTemplate) GetContents() string { return v.Contents }

// GetName returns MetricsTemplate.Name, and is useful for accessing the field via an interface.
func (v *MetricsTemplate) GetName() string { return v.Name }

// UpdateMetricsConfigResponse is returned by UpdateMetricsConfig on success.
type UpdateMetricsConfigResponse struct {
	// Update metrics config with the given configuration
	UpdateMetricsConfig string `json:"updateMetricsConfig"`
}

// GetUpdateMetricsConfig returns UpdateMetricsConfigResponse.UpdateMetricsConfig, and is useful for accessing the field via an interface.
func (v *UpdateMetricsConfigResponse) GetUpdateMetricsConfig() string { return v.UpdateMetricsConfig }

// __CreateDashboardInput is used internally by genqlient
type __CreateDashboardInput struct {
	ProjectId  string `json:"projectId"`
	BranchId   string `json:"branchId"`
	Name       string `json:"name"`
	DayRange   int    `json:"dayRange"`
	MetricsSet string `json:"metricsSet"`
}

// GetProjectId returns __CreateDashboardInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__CreateDashboardInput) GetProjectId() string { return v.ProjectId }

// GetBranchId returns __CreateDashboardInput.BranchId, and is useful for accessing the field via an interface.
func (v *__CreateDashboardInput) GetBranchId() string { return v.BranchId }

// GetName returns __CreateDashboardInput.Name, and is useful for accessing the field via an interface.
func (v *__CreateDashboardInput) GetName() string { return v.Name }

// GetDayRange returns __CreateDashboardInput.DayRange, and is useful for accessing the field via an interface.
func (v *__CreateDashboardInput) GetDayRange() int { return v.DayRange }

// GetMetricsSet returns __CreateDashboardInput.MetricsSet, and is useful for accessing the field via an interface.
func (v *__CreateDashboardInput) GetMetricsSet() string { return v.MetricsSet }

// __CreateDebugDashboardInput is used internally by genqlient
type __CreateDebugDashboardInput struct {
	ProjectId      string            `json:"projectId"`
	Config         string            `json:"config"`
	TemplateFiles  []MetricsTemplate `json:"templateFiles"`
	EmissionsFile  string            `json:"emissionsFile"`
	BranchId       string            `json:"branchId"`
	MetricsSetName string            `json:"metricsSetName"`
}

// GetProjectId returns __CreateDebugDashboardInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__CreateDebugDashboardInput) GetProjectId() string { return v.ProjectId }

// GetConfig returns __CreateDebugDashboardInput.Config, and is useful for accessing the field via an interface.
func (v *__CreateDebugDashboardInput) GetConfig() string { return v.Config }

// GetTemplateFiles returns __CreateDebugDashboardInput.TemplateFiles, and is useful for accessing the field via an interface.
func (v *__CreateDebugDashboardInput) GetTemplateFiles() []MetricsTemplate { return v.TemplateFiles }

// GetEmissionsFile returns __CreateDebugDashboardInput.EmissionsFile, and is useful for accessing the field via an interface.
func (v *__CreateDebugDashboardInput) GetEmissionsFile() string { return v.EmissionsFile }

// GetBranchId returns __CreateDebugDashboardInput.BranchId, and is useful for accessing the field via an interface.
func (v *__CreateDebugDashboardInput) GetBranchId() string { return v.BranchId }

// GetMetricsSetName returns __CreateDebugDashboardInput.MetricsSetName, and is useful for accessing the field via an interface.
func (v *__CreateDebugDashboardInput) GetMetricsSetName() string { return v.MetricsSetName }

// __GetBranchMetricsSetsInput is used internally by genqlient
type __GetBranchMetricsSetsInput struct {
	ProjectId string `json:"projectId"`
	BranchId  string `json:"branchId"`
}

// GetProjectId returns __GetBranchMetricsSetsInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__GetBranchMetricsSetsInput) GetProjectId() string { return v.ProjectId }

// GetBranchId returns __GetBranchMetricsSetsInput.BranchId, and is useful for accessing the field via an interface.
func (v *__GetBranchMetricsSetsInput) GetBranchId() string { return v.BranchId }

// __GetDashboardInput is used internally by genqlient
type __GetDashboardInput struct {
	Id string `json:"id"`
}

// GetId returns __GetDashboardInput.Id, and is useful for accessing the field via an interface.
func (v *__GetDashboardInput) GetId() string { return v.Id }

// __UpdateMetricsConfigInput is used internally by genqlient
type __UpdateMetricsConfigInput struct {
	ProjectId     string            `json:"projectId"`
	Config        string            `json:"config"`
	TemplateFiles []MetricsTemplate `json:"templateFiles"`
	Branch        string            `json:"branch"`
}

// GetProjectId returns __UpdateMetricsConfigInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__UpdateMetricsConfigInput) GetProjectId() string { return v.ProjectId }

// GetConfig returns __UpdateMetricsConfigInput.Config, and is useful for accessing the field via an interface.
func (v *__UpdateMetricsConfigInput) GetConfig() string { return v.Config }

// GetTemplateFiles returns __UpdateMetricsConfigInput.TemplateFiles, and is useful for accessing the field via an interface.
func (v *__UpdateMetricsConfigInput) GetTemplateFiles() []MetricsTemplate { return v.TemplateFiles }

// GetBranch returns __UpdateMetricsConfigInput.Branch, and is useful for accessing the field via an interface.
func (v *__UpdateMetricsConfigInput) GetBranch() string { return v.Branch }

// The mutation executed by CreateDashboard.
const CreateDashboard_Operation = `
mutation CreateDashboard ($projectId: String!, $branchId: String!, $name: String!, $dayRange: Int, $metricsSet: String) {
	createDashboard(input: {branchId:$branchId,dayRange:$dayRange,name:$name,projectId:$projectId,metricsSet:$metricsSet}) {
		id
		name
	}
}
`

func CreateDashboard(
	ctx_ context.Context,
	client_ graphql.Client,
	projectId string,
	branchId string,
	name string,
	dayRange int,
	metricsSet string,
) (data_ *CreateDashboardResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateDashboard",
		Query:  CreateDashboard_Operation,
		Variables: &__CreateDashboardInput{
			ProjectId:  projectId,
			BranchId:   branchId,
			Name:       name,
			DayRange:   dayRange,
			MetricsSet: metricsSet,
		},
	}

	data_ = &CreateDashboardResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateDebugDashboard.
const CreateDebugDashboard_Operation = `
mutation CreateDebugDashboard ($projectId: String!, $config: String!, $templateFiles: [MetricsTemplate!]!, $emissionsFile: String!, $branchId: String, $metricsSetName: String) {
	createDebugDashboard(projectId: $projectId, config: $config, templateFiles: $templateFiles, emissionsFile: $emissionsFile, branchId: $branchId, metricsSetName: $metricsSetName) {
		id
		name
	}
}
`

func CreateDebugDashboard(
	ctx_ context.Context,
	client_ graphql.Client,
	projectId string,
	config string,
	templateFiles []MetricsTemplate,
	emissionsFile string,
	branchId string,
	metricsSetName string,
) (data_ *CreateDebugDashboardResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateDebugDashboard",
		Query:  CreateDebugDashboard_Operation,
		Variables: &__CreateDebugDashboardInput{
			ProjectId:      projectId,
			Config:         config,
			TemplateFiles:  templateFiles,
			EmissionsFile:  emissionsFile,
			BranchId:       branchId,
			MetricsSetName: metricsSetName,
		},
	}

	data_ = &CreateDebugDashboardResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetBranchMetricsSets.
const GetBranchMetricsSets_Operation = `
query GetBranchMetricsSets ($projectId: String!, $branchId: String!) {
	branchConfigVersion(projectId: $projectId, branchId: $branchId) {
		metricsSets {
			name
		}
	}
}
`

func GetBranchMetricsSets(
	ctx_ context.Context,
	client_ graphql.Client,
	projectId string,
	branchId string,
) (data_ *GetBranchMetricsSetsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetBranchMetricsSets",
		Query:  GetBranchMetricsSets_Operation,
		Variables: &__GetBranchMetricsSetsInput{
			ProjectId: projectId,
			BranchId:  branchId,
		},
	}

	data_ = &GetBranchMetricsSetsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetDashboard.
const GetDashboard_Operation = `
query GetDashboard ($id: String!) {
	dashboard(id: $id) {
		id
		name
		isStale
		lastRanAt
	}
}
`

func GetDashboard(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *GetDashboardResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetDashboard",
		Query:  GetDashboard_Operation,
		Variables: &__GetDashboardInput{
			Id: id,
		},
	}

	data_ = &GetDashboardResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by UpdateMetricsConfig.
const UpdateMetricsConfig_Operation = `
mutation UpdateMetricsConfig ($projectId: String!, $config: String!, $templateFiles: [MetricsTemplate!]!, $branch: String) {
	updateMetricsConfig(projectId: $projectId, config: $config, templateFiles: $templateFiles, branch: $branch)
}
`

func UpdateMetricsConfig(
	ctx_ context.Context,
	client_ graphql.Client,
	projectId string,
	config string,
	templateFiles []MetricsTemplate,
	branch string,
) (data_ *UpdateMetricsConfigResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "UpdateMetricsConfig",
		Query:  UpdateMetricsConfig_Operation,
		Variables: &__UpdateMetricsConfigInput{
			ProjectId:     projectId,
			Config:        config,
			TemplateFiles: templateFiles,
			Branch:        branch,
		},
	}

	data_ = &UpdateMetricsConfigResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
