// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package bff

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type MetricsTemplate struct {
	Contents string `json:"contents"`
	Name     string `json:"name"`
}

// GetContents returns MetricsTemplate.Contents, and is useful for accessing the field via an interface.
func (v *MetricsTemplate) GetContents() string { return v.Contents }

// GetName returns MetricsTemplate.Name, and is useful for accessing the field via an interface.
func (v *MetricsTemplate) GetName() string { return v.Name }

// UpdateMetricsConfigResponse is returned by UpdateMetricsConfig on success.
type UpdateMetricsConfigResponse struct {
	// Update metrics config with the given configuration
	UpdateMetricsConfig string `json:"updateMetricsConfig"`
}

// GetUpdateMetricsConfig returns UpdateMetricsConfigResponse.UpdateMetricsConfig, and is useful for accessing the field via an interface.
func (v *UpdateMetricsConfigResponse) GetUpdateMetricsConfig() string { return v.UpdateMetricsConfig }

// __UpdateMetricsConfigInput is used internally by genqlient
type __UpdateMetricsConfigInput struct {
	Config        string            `json:"config"`
	TemplateFiles []MetricsTemplate `json:"templateFiles"`
}

// GetConfig returns __UpdateMetricsConfigInput.Config, and is useful for accessing the field via an interface.
func (v *__UpdateMetricsConfigInput) GetConfig() string { return v.Config }

// GetTemplateFiles returns __UpdateMetricsConfigInput.TemplateFiles, and is useful for accessing the field via an interface.
func (v *__UpdateMetricsConfigInput) GetTemplateFiles() []MetricsTemplate { return v.TemplateFiles }

// The mutation executed by UpdateMetricsConfig.
const UpdateMetricsConfig_Operation = `
mutation UpdateMetricsConfig ($config: String!, $templateFiles: [MetricsTemplate!]!) {
	updateMetricsConfig(config: $config, templateFiles: $templateFiles)
}
`

func UpdateMetricsConfig(
	ctx_ context.Context,
	client_ graphql.Client,
	config string,
	templateFiles []MetricsTemplate,
) (data_ *UpdateMetricsConfigResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "UpdateMetricsConfig",
		Query:  UpdateMetricsConfig_Operation,
		Variables: &__UpdateMetricsConfigInput{
			Config:        config,
			TemplateFiles: templateFiles,
		},
	}

	data_ = &UpdateMetricsConfigResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
