//go:build generate
// +build generate

// Package api contains the OpenAPI definition in [rerun.yml] and the autogenerated code in [client.gen.go] and
// [server.gen.go].  [generate.go] contains the commands to generate those files, and [server.cfg.yml] and
// [client.cfg.yml] contain the oapi-codegen configurations for those files.
package api

// We import the codegen package so that go mod tidy doesn't remove it.
import (
	_ "github.com/deepmap/oapi-codegen/cmd/oapi-codegen"
	_ "github.com/vektra/mockery/v2"
)

//go:generate go run github.com/deepmap/oapi-codegen/cmd/oapi-codegen --config=client.cfg.yml https://api.resim.ai/v1/openapi.yaml
//go:generate sh -c "GODEBUG=gotypesalias=0 go run github.com/vektra/mockery/v2/"
