name: Build and Test
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build:
    name: Lint and Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
      - name: Check Format
        run: if [ "$(go fmt ./... | wc -l)" -gt 0 ]; then exit 1; fi
      - name: Go Vet
        run: if ["$(go vet ./... | wc -l)" -gt 0]; then exit 1; fi
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./... -race 

  e2e:
    name: Run end-to-end test    
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
      - name: End-to-end test
        env:
          CONFIG: staging
          RESIM_CLIENT_ID: ${{ secrets.RESIM_CLIENT_ID }}
          RESIM_CLIENT_SECRET: ${{ secrets.RESIM_CLIENT_SECRET }}
        run: go test -v -tags end_to_end -count 1 ./testing