name: build-release-binary

run-name: Create Github Release for ReSim CLI

on: 
  push:
    # branches:
    # - main
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # get all tags, needed to get git log
        ref: main

    - name: setup Go Lang
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - run: |
        cd cmd/resim
        go build -ldflags "-X main.Version=${GITHUB_REF_NAME} -X main.BuiltBy=github-actions"

    - uses: ncipollo/release-action@v1.12.0
      with:
        tag: ${{ env.GITHUB_REF_NAME }}
        artifacts: "cmd/resim/resim"
        token: ${{ secrets.GITHUB_TOKEN }}